variable_names: ['Location',
                 'WindGustDir',
                 'WindDir9am',
                 'WindDir3pm',
                 'RainToday',
                 'MinTemp',
                 'Rainfall',
                 'WindGustSpeed',
                 'WindSpeed3pm',
                 'Humidity9am',
                 'Humidity3pm',
                 'Pressure9am',
                 'Date']

features_names:  ['Location',
                  'MinTemp',
                  'Rainfall',
                  'WindGustDir',
                  'WindGustSpeed',
                  'WindDir9am',
                  'WindDir3pm',
                  'WindSpeed3pm',
                  'Humidity9am',
                  'Humidity3pm', 
                  'Pressure9am',
                  'RainToday', 
                  'month',
                  'week_of_year']

float_names: ['MinTemp',
              'Rainfall',
              'WindGustSpeed',
              'WindSpeed3pm',
              'Humidity9am',
              'Humidity3pm',
              'Pressure9am']

categorical_names: ['Location',
                    'WindGustDir',
                    'WindDir9am',
                    'WindDir3pm',
                    'RainToday',
                    'month',
                    'week_of_year']
