training_optimization:
    training:
        train_name_sav: 'wA_train.sav'
        test_name_sav: 'wA_test.sav'
        features_names: ['Location',
                         'MinTemp',
                         'Rainfall',
                         'WindGustDir',
                         'WindGustSpeed',
                         'WindDir9am',
                         'WindDir3pm',
                         'WindSpeed9am',
                         'WindSpeed3pm',
                         'Humidity9am',
                          'Humidity3pm',
                         'Pressure9am',
                         'RainToday',
                         'month', 
                         'week_of_year']
        objective_name: 'RainTomorrow'
        save_data_train_test: True
        path: '../outputs/'
    optimization:
        name_sav: 'data_for_classification.sav'
        objective_name: 'delinquency_25d_1m'
        model_name: 'HistGradientBoostingClassifier'
        seed: 5000
        ratio_balance: 0.9
        test_size: 0.2
        k_folds: 4
        verbose: 10
        optimized_metric: 'cv_f1'
        complement_word: 'final'
        save_best_info: True
        path: '../outputs/'
        features_names: ['total_amount',
                         'min_saldo_actual_active_renv',
                         'age_at_application',
                         'income_source',
                         'days_since_new_account_all',
                         'application_payment_method',
                         'total_liquidez_actual_active_renv',
                         'ratio_renta_total_saldo_vencido_actual_active',
                         'apartment_type',
                         'ratio_renta_total_saldo_vencido_actual_open']